### ISSUE TITLE
Make locations interactive

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_wavi_app#148]
**Is your feature request related to a problem? Please describe.**
When you add a location to your page, It displays a map and a location title. When people are looking at your page in the app, they will see the map and title and they can expand the map to zoom and pan around.

**Describe the solution you'd like**
It would be good to be able to share this location, from the wavi app, with other apps like apple maps, google maps or to be able to open it in a browser so that you can use it to get directions to that location.

**Comment by purohitmansi** [comment]
Hello @tinashe404!

I am an openforce 2022 contributor. I would love to work on this issue and make PR as soon as I resolve the issue. Please do assign this to me.

ThankYou:)

**Comment by keyurgit45** [comment]
I would like to work on this issue @tinashe404
