### ISSUE TITLE
Enhance profile sharing

### ISSUE THREAD

**Issue by tinashe404** [atsign-foundation/at_wavi_app#162]
**Is your feature request related to a problem? Please describe.**
When you choose to share your profile by pressing Share, you are taken to wavi.ng where you are shown the sharing options.

**Describe the solution you'd like**
It would be great if you could do the following after pressing share:
- Display a QR Code on screen that other people can scan to see your profile
- Be prompted to select an app to use in order to share the URL to your profile on wavi.ng  
- Be prompted to copy your profile URL

**Video of current behaviour**
https://user-images.githubusercontent.com/69275762/156783161-a0b77d96-2cc2-41a2-a78b-18a6cb2c8f86.mov

**Comment by keyurgit45** [comment]
Hi @tinashe404 i would like to work on this issue. Can you please assign it to me?

**Comment by keyurgit45** [comment]
to share the URL, could I use the flutter_share plugin or use the current method (through wavi.ng )? @tinashe404

**Comment by tinashe404** [comment]
@keyurgit45 You can use whichever you approach you feel will achieve the intended result.
