### ISSUE TITLE
Fix images in CONTRIBUTING.md

### ISSUE THREAD

**Issue by everly-gif** [atsign-foundation/at_wavi_app#166]
**Describe the bug**

The Contributing.md file is the first file any user visits when they are new to a repository. Having clean instructions and illustrations helps the user to easily follow along the md file. However all of the images linked aren't visible and while I click on the alt text it only leads to a 404 page. This should be fixed.

**Expected behavior**

All the images should appear properly.

**Screenshots**

<img src="https://user-images.githubusercontent.com/77877486/156809308-a473cf87-46d1-43d4-8a66-c579cf41f0f9.png" width=60%>

<img src="https://user-images.githubusercontent.com/77877486/156809933-ede60f51-1f54-4324-a496-9dc4d945178e.png" width=60%>

**Comment by Ash-KODES** [comment]
Hey,I would Like to take that issue.
#open-Force 2022

**Comment by Ash-KODES** [comment]
We dont have the image folder in which mentioned images are present thats the reason why images are not redering..
Solution-1.Add required images in image folder having same heirachal level as mentioned in contributing.md
               2.remove links from contributor.md
@nitesh2599
@sarika01

**Comment by Ash-KODES** [comment]
Please Review :)
