### ISSUE TITLE
bug in the app

### ISSUE THREAD

**Issue by shubhamshah14102** [atsign-foundation/at_wavi_app#170]
**Describe the bug**
Variable element of the type AtContact prevents the app from proceding beyond the splash screen and the application just displays the logo.

**To make the app work**
1. The question mark concerned with the nullity was erased and the app works fine

Hi Sir,
I had an issue to run the app due to a minor bug which prevented the app from working fine.
I sought help from the @company mentor and he helped me correct it which enabled the app to work fine.
I would like to send a PR with the change in the code which will allow other members to install and use the app well so please can you assign this issue to me.

**Comment by yahu1031** [comment]
This was fixed with a Github reference. Need to make a release(mostly). Closing this issue.

**Comment by shubhamshah14102** [comment]
alright.
thank you
